name: avantio-test-db
version: '3.9'
services:
  postgres:
    image: postgres:16.4
    container_name: db-avantio
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: avantio-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    
volumes:
  postgres_data:

networks:
  db_network:
