version: '3.9'
services:
  avantio-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pineapples-server-app
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    container_name: pineapples-server
    command: ["npm", "run", "start:prod"]

