export enum BookingStatus {
    CONFIRMED = 'CONFIRMED',
    CANCELLED = 'CANCELLED',
    PAID = 'PAID',
    UNPAID = 'UNPAID',
    INFORMATION_REQUEST = 'INFORMATION_REQUEST',
    UNAVAILABLE = 'UNAVAILABLE',
    OWNER = 'OWNER',
    CANCELLED_BY_OWNER = 'CANCELLED_BY_OWNER',
    TPV_REQUEST = 'TPV_REQUEST',
    UNDER_REQUEST = 'UNDER_REQUEST',
    AVAILABILITY_REQUEST = 'AVAILABILITY_REQUEST',
    GUARANTEE = 'GUARANTEE',
    CONFLICTED = 'CONFLICTED',
    INVOICED = 'INVOICED',
    NON_BLOCKING = 'NONBLOCKING',
    UNKNOWN = 'UNKNOWN',
}

