name: Pine Server Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-22.04

    steps:
    # Etapa 1: Checkout do código
    - name: Checkout Code
      uses: actions/checkout@v3

    # Etapa 2: Configurar SSH para acesso ao servidor
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PINE_SERVER }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 200.152.109.148 >> ~/.ssh/known_hosts

    # Etapa 3: Instalar o Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Etapa 4: Construir e salvar a imagem Docker usando o Docker Compose
    - name: Build and Save Docker Image
      run: |
        docker-compose -f pine-serve/docker-compose.yml build
        docker save pineapples-server-app -o avantio-backend.tar

    # Etapa 5: Enviar o arquivo da imagem para o servidor
    - name: Transfer Docker Image to Server
      run: |
        scp -v avantio-backend.tar root@200.152.109.148:/tmp/avantio-backend.tar
    
    # Etapa 6: Fazer o deploy no servidor
    - name: Deploy Backend
      run: |
        ssh root@200.152.109.148 << 'EOF'
          docker load < /tmp/avantio-backend.tar
          docker-compose -f /path/to/docker-compose.yml up -d --no-deps avantio-app
          rm /tmp/avantio-backend.tar
        EOF

    # Etapa 7: Limpeza no ambiente local do runner
    - name: Clean Up Local Artifacts
      run: rm avantio-backend.tar