name: Pine Dashboard

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'dashs/dash-limpeza/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build dash-limpeza
        working-directory: ./dashs/dash-limpeza
        run: |
          npm install
          npm run build

      - name: Build and push Docker image for dash-limpeza
        run: |
          docker build -t henrique27/pine-server-application:tagname/dash-limpeza ./dashs/dash-limpeza
          docker push henrique27/pine-server-application:tagname/dash-limpeza

      - name: Deploy to DigitalOcean
        env:
          DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        run: |
          sshpass -p "$DIGITALOCEAN_PASSWORD" ssh -o StrictHostKeyChecking=no root@167.172.106.156 "docker pull henrique27/pine-server-application:tagname/dash-limpeza && docker-compose -f /path/to/docker-compose.yml up -d"
